export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const DISPATCH_AGREEMENT = "DISPATCH_AGREEMENT";
export const DISPATCH_NEW_FILES = "DISPATCH_NEW_FILES";
export const DISPATCH_NETWORK = "DISPATCH_NETWORK";
export const DISPATCH_STOP_UPLOAD = "DISPATCH_STOP_UPLOAD";
export const DISPATCH_USER_ACTIONS = "DISPATCH_USER_ACTIONS";
export const GET_APPVER = "GET_APPVER";
export const SET_USER = "SET_USER";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_ENCRYPTION_KEY = "SET_ENCRYPTION_KEY";
export const GET_ALL_FILES = "GET_ALL_FILES";
export const GET_ALL_REPORTS = "GET_ALL_REPORTS";
export const GET_DETAIL_OF_REPORT = "GET_DETAIL_OF_REPORT";
export const GET_DETAIL_OF_REPORT_COUNTRY = "GET_DETAIL_OF_REPORT_COUNTRY";
export const GET_ENCRYPTION_KEY_FALSE = "GET_ENCRYPTION_KEY_FALSE";
export const GET_ENCRYPTION_KEY_TRUE = "GET_ENCRYPTION_KEY_TRUE";
export const GET_FILES = "GET_FILES";
export const GET_FILES_STATUS = "GET_FILES_STATUS";
export const GET_FILES_UPLOADED_STORAGE_USAGE =
  "GET_FILES_UPLOADED_STORAGE_USAGE";
export const GET_PROFESSIONAL_USERS = "GET_PROFESSIONAL_USERS";
export const GET_SPREADSHEET = "GET_SPREADSHEET";
export const GET_STATEMENTS = "GET_STATEMENTS";
export const GET_USER_ACTIONS_DETAILS = "GET_USER_ACTIONS_DETAILS";
export const GET_USER_ACTIONS_INDIVIDUAL = "GET_USER_ACTIONS_INDIVIDUAL";
export const GET_USER_ACTIONS_OVERVIEW = "GET_USER_ACTIONS_OVERVIEW";
export const GET_USERS_BELONG_PRO_USER = "GET_USERS_BELONG_PRO_USER";
export const SNACKBAR = "SNACKBAR";

export default {
  CHANGE_PASSWORD,
  DISPATCH_AGREEMENT,
  DISPATCH_NEW_FILES,
  DISPATCH_NETWORK,
  DISPATCH_STOP_UPLOAD,
  DISPATCH_USER_ACTIONS,
  GET_APPVER,
  SET_USER,
  SET_USER_INFO,
  SET_ENCRYPTION_KEY,
  GET_ALL_FILES,
  GET_ALL_REPORTS,
  GET_DETAIL_OF_REPORT,
  GET_DETAIL_OF_REPORT_COUNTRY,
  GET_ENCRYPTION_KEY_FALSE,
  GET_ENCRYPTION_KEY_TRUE,
  GET_FILES,
  GET_FILES_STATUS,
  GET_FILES_UPLOADED_STORAGE_USAGE,
  GET_PROFESSIONAL_USERS,
  GET_SPREADSHEET,
  GET_STATEMENTS,
  GET_USER_ACTIONS_DETAILS,
  GET_USER_ACTIONS_INDIVIDUAL,
  GET_USER_ACTIONS_OVERVIEW,
  GET_USERS_BELONG_PRO_USER,
  SNACKBAR,
};
